version: '3.7'

services:
  bn-mlworkspace-gpu2:
      build:
        context: ./
        dockerfile: ./Dockerfile.wsi.gpu
      environment:
        NVIDIA_DISABLE: 1
      volumes:
        - ml-workspace:/workspace
        - D:\:/host_Data
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 8080:8080
        - 5151:5151
        - 8001:8001
        - 5001:5001
      restart: unless-stopped
      deploy:
        resources:
          reservations:
            devices:
            - capabilities: [gpu]
volumes:
  ml-workspace:  
